name: Upload Release

on:
  push:
    tags:
    - v* # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Get the version # https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32163/highlight/true#M1024
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    # save and upload release-upload-url in an artifact file (shared between jobs)
    - shell: bash
        run: |
          echo ${{ steps.create_release.outputs.upload_url }} > release-upload-url.txt
    - name: Upload release-upload-url
        uses: actions/upload-artifact@v1
        with:
          name: release-upload-url
          path: release-upload-url.txt
    # save and upload version in an artifact file (shared between jobs)
    - shell: bash
        run: |
          echo ${{ steps.get_version.outputs.VERSION }} > release-version.txt
    - name: Upload release-version
        uses: actions/upload-artifact@v1
        with:
          name: release-version
          path: release-version.txt

  build_linux:
    needs: create_release
    name: Build for GNU/Linux
    runs-on: ubuntu-latest

    # we build statically linked binaries using the official
    # Crystal alpine-linux docker image
    # (we need musl-libc, hence we use Alpine)
    # https://crystal-lang.org/2020/02/02/alpine-based-docker-images.html
    container:
      image: crystallang/crystal:latest-alpine

    steps:
    - uses: actions/checkout@v2

    # get artifacts containing release-upload-url and release-version
    - name: Download release-upload-url
        uses: actions/download-artifact@v1
        with:
          name: release-upload-url
    - name: Download release-version
        uses: actions/download-artifact@v1
        with:
          name: release-version

    - name: Install dependencies
      run: shards install
    - name: Build
      run: shards build --production --static
    - name: Create archive
      run: tar -czf nanvault-$(cat release-version/release-version.txt)-linux-amd64.tar.gz -C ./bin . 

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: $(cat release-upload-url/release-upload-url.txt)
        asset_path: ./nanvault-$(cat release-version/release-version.txt)-linux-amd64.tar.gz
        asset_name: nanvault-$(cat release-version/release-version.txt)-linux-amd64.tar.gz
        asset_content_type: application/gzip

  build_macos:
    needs: create_release
    name: Build for macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    # get artifacts containing release-upload-url and release-version
    - name: Download release-upload-url
        uses: actions/download-artifact@v1
        with:
          name: release-upload-url
    - name: Download release-version
        uses: actions/download-artifact@v1
        with:
          name: release-version

    - name: Brew update
      run: brew update
    - name: Install Crystal
      run: brew install crystal

    - name: Install dependencies
      run: shards install
    - name: Build
      run: shards build --production # no static linking on macOS: https://developer.apple.com/library/archive/qa/qa1118/_index.html
    - name: Create archive
      run: tar -czf nanvault-$(cat release-version/release-version.txt)-darwin-amd64.tar.gz -C ./bin . 

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: $(cat release-upload-url/release-upload-url.txt)
        asset_path: ./nanvault-$(cat release-version/release-version.txt)-darwin-amd64.tar.gz
        asset_name: nanvault-$(cat release-version/release-version.txt)-darwin-amd64.tar.gz
        asset_content_type: application/gzip
         
